name: weight_tracker
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter
  numberpicker: "^0.1.0"
  firebase_auth: "^0.5.10"
  firebase_database: "^0.4.6"
  firebase_analytics: "^1.0.1"
  redux: "^3.0.0"
  flutter_redux: "^0.5.0"
  tuple: "^1.0.1"
  intl: "^0.15.6"
  shared_preferences: "^0.4.1"
  mockito: "3.0.0-beta+3"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/scale-bathroom.png